DoAnChuyenNganh/Controllers/QuanLyKhoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DoAnChuyenNganh.Models;
namespace DoAnChuyenNganh.Controllers
{
    [Authorize(Roles = "QuanTri,QuanLyKho")]
    public class QuanLyKhoController : Controller
    {
        Ship2hEntities db = new Ship2hEntities();
        // GET: QuanLyKho
        public ActionResult Index()
        {
            if (Session["TaiKhoan"] != null)
            {
                return View(db.Khoes.OrderBy(n => n.MaKho));
            }
            else
            {
                return RedirectToAction("DangNhap", "Home");
            }

        }

        public ActionResult ThemKho()
        {
            ViewBag.MaKhuVuc = new SelectList(db.KhuVucs.OrderBy(n => n.TenKhuVuc), "MaKhuVuc", "TenKhuVuc");
            if (Session["TaiKhoan"] != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("DangNhap", "Home");
            }
        }
        [ValidateInput(false)]
        [HttpPost]
        public ActionResult ThemKho(Kho kho)
        {
            ViewBag.MaKhuVuc = new SelectList(db.KhuVucs.OrderBy(n => n.TenKhuVuc), "MaKhuVuc", "TenKhuVuc");
            db.Khoes.Add(kho);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult ChinhSua(int? id)
        {
            if (Session["TaiKhoan"] != null)
            {
                if (id == null)
                {
                    Response.StatusCode = 404;
                    return null;
                }
                Kho kho = db.Khoes.SingleOrDefault(n => n.MaKho == id);
                if (kho == null)
                {
                    return HttpNotFound();
                }
                ViewBag.MaKhuVuc = new SelectList(db.KhuVucs.OrderBy(n => n.TenKhuVuc), "MaKhuVuc", "TenKhuVuc", kho.MaKhuVuc);
                return View(kho);
            }
            else
            {
                return RedirectToAction("DangNhap", "Home");
            }
        }
        [ValidateInput(false)]
        [HttpPost]
        public ActionResult ChinhSua(Kho kho)
        {
            ViewBag.MaKhuVuc = new SelectList(db.KhuVucs.OrderBy(n => n.TenKhuVuc), "MaKhuVuc", "TenKhuVuc", kho.MaKhuVuc);
            db.Entry(kho).State = System.Data.Entity.EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Xoa(int? id)
        {
            if (Session["TaiKhoan"] != null)
            {
                if (id == null)
                {
                    Response.StatusCode = 404;
                    return null;
                }
                Kho kho = db.Khoes.SingleOrDefault(n => n.MaKho == id);
                if (kho == null)
                {
                    return HttpNotFound();
                }
                ViewBag.TenKhuVuc = new SelectList(db.KhuVucs.OrderBy(n => n.TenKhuVuc), "MaKhuVuc", "TenKhuVuc", kho.MaKhuVuc);
                return View(kho);
            }
            else
            {
                return RedirectToAction("DangNhap", "Home");
            }
        }
        [HttpPost]
        public ActionResult Xoa(int id)
        {

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Kho kho = db.Khoes.SingleOrDefault(n => n.MaKho == id);
            if (kho == null)
            {
                return HttpNotFound();
            }
            try
            {
                db.Khoes.Remove(kho);
                db.SaveChanges();
                return RedirectToAction("Index");
            }catch
            {
                ViewBag.ThongBao = "Thông tin kho có dữ liệu liên quan đến shipper hoặc đơn hàng nên chưa thể xóa";
                return View(kho);
            }
            
        }
        [HttpGet]
        public ActionResult XemSoLuongMatHang(int? id)
        {
            if (Session["TaiKhoan"] != null)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Kho model = db.Khoes.SingleOrDefault(n => n.MaKho == id);
                if (model == null)
                {
                    return HttpNotFound();
                }
                var listChiTietMH = db.ChiTietMatHangs.Where(n => n.MaKho == id);
                ViewBag.ListChiTietMH = listChiTietMH;
                return View(model);
            }
            else
            {
                return RedirectToAction("DangNhap", "Home");
            }
        }
        public ActionResult XemShipper(int? id)
        {
            if (Session["TaiKhoan"] != null)
            {

                return View(db.Shippers.Where(n => n.MaKho == id));
            }
            else
            {
                return RedirectToAction("DangNhap", "Home");
            }
        }
        public ActionResult XemDonHangChuaGiao(int? id)
        {
            if (Session["TaiKhoan"] != null)
            {
                ViewBag.TongThoiGianGiao = db.DonDatHangs.Where(n => n.MaShipper == id && n.TinhTrangGiaoHang == false).Sum(n => n.ThoiGianGiao);
                ViewBag.idShipper = id;
                if (ViewBag.TongThoiGianGiao != null)
                {
                    float a = (float)ViewBag.TongThoiGianGiao;
                    if (a > 90)
                    {
                        ViewBag.ThongBaoXemDonHang = "Thời gian đã vượt quá 90 phút xem xét giao cho shipper khác";
                        return View(db.DonDatHangs.Where(n => n.MaShipper == id && n.TinhTrangGiaoHang == false && n.ThoiGianGiao != null));
                    }
                    ViewBag.ThongBaoXemDonHang1 = "Thời gian hợp lý để đi giao";
                    return View(db.DonDatHangs.Where(n => n.MaShipper == id && n.TinhTrangGiaoHang == false && n.ThoiGianGiao != null));
                }
                return View(db.DonDatHangs.Where(n => n.MaShipper == id && n.TinhTrangGiaoHang == false && n.ThoiGianGiao != null));
            }
            else
            {
                return RedirectToAction("DangNhap", "Home");
            }
        }
        public ActionResult DonHangChuaCoShipperKho(int? id)
        {
            if (Session["TaiKhoan"] != null)
            {
                ViewBag.idKho = id;
                return View(db.DonDatHangs.Where(n => n.MaShipper == null && n.MaKho == id && n.ThoiGianGiao != null));
            }
            else
            {
                return RedirectToAction("DangNhap", "Home");
            }
        }
        public ActionResult DonHangChuaTinhThoiGian(int? id)
        {
            if (Session["TaiKhoan"] != null)
            {
                return View(db.DonDatHangs.Where(n => n.MaShipper == null && n.MaKho == id && n.ThoiGianGiao == null));
            }
            else
            {
                return RedirectToAction("DangNhap", "Home");
            }
        }
        public ActionResult DonHangDaGiao(int? id)
        {
            if (Session["TaiKhoan"] != null)
            {
                ViewBag.idShipper = id;
                return View(db.DonDatHangs.Where(n => n.MaShipper == id && n.TinhTrangGiaoHang == true));
            }
            else
            {
                return RedirectToAction("DangNhap", "Home");
            }
        }
        [HttpGet]
        public ActionResult TinhThoiGian(int? id)
        {

            if (Session["TaiKhoan"] != null)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                DonDatHang model = db.DonDatHangs.SingleOrDefault(n => n.MaDonDatHang == id);
                if (model == null)
                {
                    return HttpNotFound();
                }
                var listChiTietDH = db.ChiTietDonDatHangs.Where(n => n.MaDonDatHang == id);
                ViewBag.ListChiTietDH = listChiTietDH;
                return View(model);
            }
            else
            {
                return RedirectToAction("DangNhap", "Home");
            }
        }
        [HttpPost]
        public ActionResult TinhThoiGian(DonDatHang ddh)
        {
            DonDatHang ddhUpdate = db.DonDatHangs.Single(n => n.MaDonDatHang == ddh.MaDonDatHang);
            ddhUpdate.ThoiGianGiao = ddh.ThoiGianGiao;
            db.SaveChanges();
            var listChiTietDH = db.ChiTietDonDatHangs.Where(n => n.MaDonDatHang == ddh.MaDonDatHang);
            ViewBag.ListChiTietDH = listChiTietDH;
            ViewBag.ThongBaoDuyetThoiGian = "Đã lưu thành công";
            return View(ddhUpdate);
        }
        [HttpGet]
        public ActionResult GoShipper(int? id)
        {
            if (Session["TaiKhoan"] != null)
            {
                if (id == null)
                {
                    Response.StatusCode = 404;
                    return null;
                }
                DonDatHang ddh = db.DonDatHangs.Where(n=>n.ThoiGianDat!=null&&n.TinhTrangGiaoHang==false&&n.MaShipper!=null).SingleOrDefault(n => n.MaDonDatHang == id);
                if (ddh == null)
                {
                    return HttpNotFound();
                }
                return View(ddh);
            }
            else
            {
                return RedirectToAction("DangNhap", "Home");
            }
        } 
        [HttpPost]
        public ActionResult GoShipper(int id)
        {   
            DonDatHang ddhUpdate = db.DonDatHangs.Single(n => n.MaDonDatHang == id);
            ddhUpdate.MaShipper = null;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult ChonShipper(int? id)

DoAnChuyenNganh/Views/QuanLyKho/ChinhSua.cshtml
@model DoAnChuyenNganh.Models.Kho
@{
    ViewBag.Title = "ChỉnhSửa";
    Layout = "~/Views/Layout/HomeLayout.cshtml";
}


<h3 class="title1">Chỉnh sửa kho</h3>

<div class="form-three widget-shadow">
    @using (Html.BeginForm("ChinhSua", "QuanLyKho", FormMethod.Post, new { @enctype = "multipart/form-data", @class = "form-horizontal" }))
    {
        @Html.AntiForgeryToken()
        @Html.Hidden("MaKho", Model.MaKho);
        <div class="form-group">
            <label for="focusedinput" class="col-sm-2 control-label">Tên Kho</label>
            <div class="col-sm-8">
                @Html.EditorFor(model => model.TenKho, new { htmlAttributes = new { @class = "form-control", @placeholder = "Nhập tên kho" } })
            </div>
        </div>
        <div class="form-group">
            <label for="focusedinput" class="col-sm-2 control-label">Địa chỉ</label>
            <div class="col-sm-8">
                @Html.EditorFor(model => model.DiaChi, new { htmlAttributes = new { @class = "form-control", @placeholder = "Nhập địa chỉ" } })
            </div>
        </div>
        <div class="form-group">
            <label for="focusedinput" class="col-sm-2 control-label">Định vị kho</label>
            <div class="col-sm-8">
                @Html.EditorFor(model => model.DinhViKho, new { htmlAttributes = new { @class = "form-control", @placeholder = "Nhập định vị" } })
            </div>
        </div>
        <div class="form-group">
            <label for="focusedinput" class="col-sm-2 control-label">Thuộc khu vực</label>
            <div class="col-sm-8">
                @Html.DropDownList("MaKhuVuc", null, new { @class = "form-control" })
            </div>
        </div>
        <button type="submit" class="btn btn-default">Chỉnh Sửa Thông Tin Kho</button>
    }
</div>
<div>
    @Html.ActionLink("Quay lại danh sách", "Index")
</div>

DoAnChuyenNganh/Views/QuanLyKho/ChonShipper.cshtml
@using DoAnChuyenNganh.Models
@model DonDatHang
@{
    ViewBag.Title = "Chọn Shipper";
    Layout = "~/Views/Layout/HomeLayout.cshtml";
}

<h2>Thông tin đơn hàng thuộc <font color="#f65e84">@Model.Kho.TenKho</font></h2>
<div class="form-three widget-shadow">
    @using (Html.BeginForm())
    {
        @Html.Hidden("MaDonDatHang", Model.MaDonDatHang);
        @Html.AntiForgeryToken()
        <table class="table table-hover" id="table">
            <tr>
                <td colspan="4">
                    <table style="width:100%;">
                        <tr>
                            <td>Mã đơn đặt hàng: <b style="color:red;">@Model.MaDonDatHang</b></td>
                            <td>Thời gian đặt: <b style="color:red;">@Model.ThoiGianDat </b></td>
                            <td>Nơi giao: <b style="color:red;">@Model.DinhViKhachHang </b></td>
                        </tr>
                    </table>
                </td>
            </tr>
        </table>
        <div class="form-group">
            <label for="focusedinput" class="col-sm-2 control-label">Chọn shipper theo mã</label>
            <div class="col-sm-8">
                @Html.DropDownList("MaShipper", null, new { @class = "form-control" })
            </div>
            <button type="submit" class="btn btn-default">Lưu thông tin</button>
        </div>
        <div class="panel-body widget-shadow">
            @{ IEnumerable<Shipper> listShipper = (IEnumerable<Shipper>)ViewBag.listShipper;}
            <h4>Danh sách shipper thuộc kho <font color="#f65e84">@Model.Kho.TenKho</font> đang rảnh</h4>
            <table class="table">
                <thead>
                    <tr>
                        <th>Mã Shipper</th>
                        <th>Họ tên</th>
                        <th>Thuộc Kho</th>
                        <th>Ca làm</th>
                        <th>Đang giao hàng</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in listShipper)
                    {
                        <tr>
                            <td>
                                @item.MaShipper
                            </td>
                            <td>
                                @item.HoTen
                            </td>
                            
                            <td>
                                @item.Kho.TenKho
                            </td>
                            <td>
                                @item.CaLam.CaLam1
                            </td>
                            <td>
                                @item.DangDiGiao
                            </td>
                        </tr>
                    }

                </tbody>
            </table>
        </div>
    }
</div>

DoAnChuyenNganh/Views/QuanLyKho/DonHangChuaCoShipperKho.cshtml
@using DoAnChuyenNganh.Models;
@model IEnumerable<DonDatHang>
@{
    ViewBag.Title = "Đơn hàng chưa có Shipper Kho";
    Layout = "~/Views/Layout/HomeLayout.cshtml";
    WebGrid grid = new WebGrid(source: Model, rowsPerPage: 5);
}

<h2 class="title1">Quản lý kho (Đơn hàng chưa có shipper)</h2>
<br />
<div>
    @Html.ActionLink("Quay lại danh sách", "Index")
</div>
<br />


@grid.GetHtml(
       tableStyle: "divTable",
       headerStyle: "gridHead",
       footerStyle: "gridFooter",
       rowStyle: "gridRow",
       alternatingRowStyle: "gridAltRow",
        columns: grid.Columns(
               grid.Column("MaDonDatHang", header: "Mã đơn"),
               grid.Column("MaShipper", header: "Tên Shipper", format: p => p.MaShipper != null ? p.Shipper.HoTen : ""),
               grid.Column("MaKho", header: "Thuộc Kho", format: p => p.MaKho != null ? p.Kho.TenKho : ""),
               grid.Column("ThoiGianDat", header: "Ngày đặt"),
               grid.Column("DinhViKhachHang", "Định vị khách hàng"),
               grid.Column("ThoiGianGiao", header: "Thời gian dự kiến giao (phút)"),
               grid.Column(format: p => Html.ActionLink("Chọn Shipper", "ChonShipper", new { id = p.MaDonDatHang }, new { @target = "banml" }))

               ))
<style>
    .divTable {
        border: 1px solid #999999;
        width: 100%;
    }

        .divTable td {
            border: 1px solid #999999;
        }

    .gridHead {
        background-color: Green;
    }

        .gridHead > th > a {
            color: #fff;
        }

    .gridFooter {
        font-weight: bold;
    }
    /*.gridRow{
            color: #fff;
            background-color: blueviolet;
        }
        .gridAltRow{
            color: #fff;
            background-color: darkorange;
        }*/
</style>
<style>
    .FooterAdmin {
        display: none;
    }

    .tabs {
        display: flex;
    }

    .tablinks {
        border: none;
        outline: none;
        cursor: pointer;
        width: 100%;
        padding: 1rem;
        font-size: 13px;
        text-transform: uppercase;
        font-weight: 600;
        transition: 0.2s ease;
    }

        .tablinks:hover {
            background: aqua;
            color: #fff;
        }
        /* Tab active */
        .tablinks.active {
            background: aqua;
            color: #fff;
        }

    /* tab content */
    .tabcontent {
        display: none;
    }
        /* Text*/
        .tabcontent p {
            color: #333;
            font-size: 16px;
        }
        /* tab content active */
        .tabcontent.active {
            display: block;
        }
</style>

DoAnChuyenNganh/Views/QuanLyKho/DonHangChuaTinhThoiGian.cshtml
@using DoAnChuyenNganh.Models;
@model IEnumerable<DonDatHang>
@{
    ViewBag.Title = "Đơn hàng chưa tính thời gian";
    Layout = "~/Views/Layout/HomeLayout.cshtml";
    WebGrid grid = new WebGrid(source: Model, rowsPerPage: 5);
}

<h2 class="title1">Quản lý đơn kho (Đơn hàng chưa tính thời gian)</h2>
<br />
<div>
    @Html.ActionLink("Quay lại danh sách", "Index")
</div>
<br />
@grid.GetHtml(
       tableStyle: "divTable",
       headerStyle: "gridHead",
       footerStyle: "gridFooter",
       rowStyle: "gridRow",
       alternatingRowStyle: "gridAltRow",
        columns: grid.Columns(
               grid.Column("MaDonDatHang", header: "Mã đơn"),
              
               grid.Column("MaKho", header: "Thuộc Kho", format: p => p.MaKho != null ? p.Kho.TenKho : ""),
               grid.Column("ThoiGianDat", header: "Ngày đặt"),
               grid.Column("DinhViKhachHang", "Định vị khách hàng"),
               grid.Column("ThoiGianGiao", header: "Thời gian dự kiến giao (phút)"),
               grid.Column(format: p => Html.ActionLink("Tính thời gian", "TinhThoiGian", new { id = p.MaDonDatHang }, new { @target = "banml" }))

               ))
<style>
    .divTable {
        border: 1px solid #999999;
        width: 100%;
    }

        .divTable td {
            border: 1px solid #999999;
        }

    .gridHead {
        background-color: Green;
    }

        .gridHead > th > a {
            color: #fff;
        }

    .gridFooter {
        font-weight: bold;
    }
    /*.gridRow{
            color: #fff;
            background-color: blueviolet;
        }
        .gridAltRow{
            color: #fff;
            background-color: darkorange;
        }*/
</style>
<style>
    .FooterAdmin {
        display: none;
    }

    .tabs {
        display: flex;
    }

    .tablinks {
        border: none;
        outline: none;
        cursor: pointer;
        width: 100%;
        padding: 1rem;
        font-size: 13px;
        text-transform: uppercase;
        font-weight: 600;
        transition: 0.2s ease;
    }

        .tablinks:hover {
            background: aqua;
            color: #fff;
        }
        /* Tab active */
        .tablinks.active {
            background: aqua;
            color: #fff;
        }

    /* tab content */
    .tabcontent {
        display: none;
    }
        /* Text*/
        .tabcontent p {
            color: #333;
            font-size: 16px;
        }
        /* tab content active */
        .tabcontent.active {
            display: block;
        }
</style>

DoAnChuyenNganh/Views/QuanLyKho/DonHangDaGiao.cshtml
@using DoAnChuyenNganh.Models;
@model IEnumerable<DonDatHang>
@{
    ViewBag.Title = "Đơn hàng đã giao";
    Layout = "~/Views/Layout/HomeLayout.cshtml";
    WebGrid grid = new WebGrid(source: Model, rowsPerPage: 10);
}

<h2 class="title1">Danh sách đơn đặt hàng</h2>
<ul class="tabs">
    <li role="presentation" class="tablinks ">@Html.ActionLink("Xem đơn hàng chưa giao", "XemDonHangChuaGiao", new { id = ViewBag.idShipper })"</li>
    <li role="presentation" class="tablinks active">@Html.ActionLink("Xem đơn hàng đã giao", "DonHangDaGiao", new { id = ViewBag.idShipper })</li>

</ul>
<br />
@*Thể hiện dữ liệu thông qua control Webgrid*@
@grid.GetHtml(
         tableStyle: "divTable",
         headerStyle: "gridHead",
         footerStyle: "gridFooter",
         rowStyle: "gridRow",
         alternatingRowStyle: "gridAltRow",
         columns: grid.Columns(
            grid.Column("MaDonDatHang", "Mã Đơn Đặt Hàng"),
            grid.Column("MaShipper", header: "Tên Shipper", format: p => p.MaShipper != null ? p.Shipper.HoTen : ""),
            grid.Column("ThoiGianDat", "Thời gian đặt"),
            grid.Column("DaThanhToan", "Tình trạng thanh toán"),
            grid.Column("ThoiGianGiao", "Dự tính thời gian giao"),
            grid.Column("TinhTrangGiaoHang", "Tình trạng giao hàng"),
            grid.Column("DinhViKhachHang", "Định vị khách hàng"),
            grid.Column(format: p => Html.ActionLink("Gỡ Shipper", "GoShipper", new { id = p.MaDonDatHang }))
            ))
<style>
    .divTable {
        border: 1px solid #999999;
        width: 100%;
    }

        .divTable td {
            border: 1px solid #999999;
        }

    .gridHead {
        background-color: Green;
    }

        .gridHead > th > a {
            color: #fff;
        }

    .gridFooter {
        font-weight: bold;
    }
    /*.gridRow{
            color: #fff;
            background-color: blueviolet;
        }
        .gridAltRow{
            color: #fff;
            background-color: darkorange;
        }*/
</style>
<style>
    .FooterAdmin {
        display: none;
    }

    .tabs {
        display: flex;
    }

    .tablinks {
        border: none;
        outline: none;
        cursor: pointer;
        width: 100%;
        padding: 1rem;
        font-size: 13px;
        text-transform: uppercase;
        font-weight: 600;
        transition: 0.2s ease;
    }

        .tablinks:hover {
            background: aqua;
            color: #fff;
        }
        /* Tab active */
        .tablinks.active {
            background: aqua;
            color: #fff;
        }

    /* tab content */
    .tabcontent {
        display: none;
    }
        /* Text*/
        .tabcontent p {
            color: #333;
            font-size: 16px;
        }
        /* tab content active */
        .tabcontent.active {
            display: block;
        }
</style>

DoAnChuyenNganh/Views/QuanLyKho/GoShipper.cshtml
@model DoAnChuyenNganh.Models.DonDatHang
@{
    ViewBag.Title = "Gỡ Shipper";
    Layout = "~/Views/Layout/HomeLayout.cshtml";
}

<h3 class="title1">Gỡ đơn hàng @Html.DisplayFor(model=>model.MaDonDatHang) khỏi shipper @Html.DisplayFor(model => model.Shipper.HoTen)</h3>
<h4 class=" text-danger">Bạn có chắc muốn gỡ shipper chứ?</h4>

<br/>
<div class="blank-page widget-shadow scroll" id="style-2 div1">
    <h4> Thông tin đơn đặt hàng </h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Mã đơn đặt hàng
        </dt>
        <dd>
            @Html.DisplayFor(model => model.MaDonDatHang)
        </dd>
        <dt>
            Tên shipper phụ trách
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Shipper.HoTen)
        </dd>
    </dl>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
<div class="form-actions no-color">
    <input type="submit" value="Gỡ shipper" class="btn btn-warning" /> |
    @Html.ActionLink("Quay lại danh sách", "XemDonHangChuaGiao", new { id = Model.MaShipper})
</div>
     }
</div>

DoAnChuyenNganh/Views/QuanLyKho/ThemKho.cshtml
@model DoAnChuyenNganh.Models.Kho
@{
    ViewBag.Title = "Thêm Kho";
    Layout = "~/Views/Layout/HomeLayout.cshtml";
}

<h3 class="title1">Thêm kho</h3>

<div class="form-three widget-shadow">
    @using (Html.BeginForm("ThemKho", "QuanLyKho", FormMethod.Post, new { @enctype = "multipart/form-data", @class = "form-horizontal" }))
    {
        @Html.AntiForgeryToken()
        <div class="form-group">
            <label for="focusedinput" class="col-sm-2 control-label">Tên Kho</label>
            <div class="col-sm-8">
                @Html.EditorFor(model => model.TenKho, new { htmlAttributes = new { @class = "form-control", @placeholder = "Nhập tên kho" } })
            </div>
        </div>
        <div class="form-group">
            <label for="focusedinput" class="col-sm-2 control-label">Địa chỉ</label>
            <div class="col-sm-8">
                @Html.EditorFor(model => model.DiaChi, new { htmlAttributes = new { @class = "form-control", @placeholder = "Nhập địa chỉ" } })
            </div>
        </div>
        <div class="form-group">
            <label for="focusedinput" class="col-sm-2 control-label">Định vị kho</label>
            <div class="col-sm-8">
                @Html.EditorFor(model => model.DinhViKho, new { htmlAttributes = new { @class = "form-control", @placeholder = "Nhập định vị" } })
            </div>
        </div>
        <div class="form-group">
            <label for="focusedinput" class="col-sm-2 control-label">Thuộc khu vực</label>
            <div class="col-sm-8">
                @Html.DropDownList("MaKhuVuc", null, new { @class = "form-control" })
            </div>
        </div>
        <button type="submit" class="btn btn-default">Thêm Kho</button>
    }
</div>
<div>
    @Html.ActionLink("Quay lại danh sách", "Index")
</div>

DoAnChuyenNganh/Views/QuanLyKho/XemShipper.cshtml
@using DoAnChuyenNganh.Models;
@model IEnumerable<Shipper>

@{
    ViewBag.Title = "Xem Shipper";
    Layout = "~/Views/Layout/HomeLayout.cshtml";
}

<h2>Xem danh sách shipper</h2>
<div class="panel-body widget-shadow">
    <h4>Danh sách shipper :</h4>
    <table class="table">
        <thead>
            <tr>
                <th>Mã Shipper</th>
                <th>Họ tên</th>
                <th>Thuộc Kho</th>
                <th>Ca làm</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.MaShipper)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.HoTen)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Kho.TenKho)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CaLam.CaLam1)
                    </td>
                    <td>
                        @Html.ActionLink("Xem danh sách đơn hàng phân công", "XemDonHangChuaGiao", new { id = item.MaShipper }) 
              
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>